### ISSUE TITLE
SMLHelper minor changes

### ISSUE THREAD

**Issue by AlexejheroYTB** [QModManager/QModManager#102]

**Comment by AlexejheroYTB** [comment]
- [Handlers/CraftDataHandler.cs#L21-L43](../blob/dev/3.0/QModManager/API/SMLHelper/Handlers/CraftDataHandler.cs#L21-L43) - Duplicate `SetTechData` method. Class `TechData` inherits from `ITechData`

**Comment by AlexejheroYTB** [comment]
- [Handlers/CraftDataHandler.cs#L151](../blob/dev/3.0/QModManager/API/SMLHelper/Handlers/CraftDataHandler.cs#L151) & [Handlers/CraftDataHandler.cs#L347](../blob/dev/3.0/QModManager/API/SMLHelper/Handlers/CraftDataHandler.cs#L347) - Parameter `backgroundColor` should be renamed to `backgroundType`

**Comment by AlexejheroYTB** [comment]
- [Handlers/CraftDataHandler.cs#L165-L188](../blob/dev/3.0/QModManager/API/SMLHelper/Handlers/CraftDataHandler.cs#L165-L188) & [Handlers/CraftDataHandler.cs#L361-L384](../blob/dev/3.0/QModManager/API/SMLHelper/Handlers/CraftDataHandler.cs#L361-L384) - Parameter `techType` should be the first parameter

**Comment by AlexejheroYTB** [comment]
- [Handlers/CustomFishHandler.cs](../blob/dev/3.0/QModManager/API/SMLHelper/Handlers/CustomFishHandler.cs) - File can be renamed to `FishHandler.cs`

**Comment by AlexejheroYTB** [comment]
- [Handlers/CustomFishHandler.cs#L26](../blob/dev/3.0/QModManager/API/SMLHelper/Handlers/CustomFishHandler.cs#L26) - Does this need to be public?

**Comment by AlexejheroYTB** [comment]
- [Handlers/PDAHandler.cs#L40-L43](https://github.com/QModManager/QModManager/blob/dev/3.0/QModManager/API/SMLHelper/Handlers/PDAHandler.cs#L40-L43) - If `fragmentCount` is smaller than `0`, it should default to `0`, not to `1`

**Comment by PrimeSonic** [comment]
>    [Handlers/PDAHandler.cs#L40-L43](https://github.com/QModManager/QModManager/blob/dev/3.0/QModManager/API/SMLHelper/Handlers/PDAHandler.cs#L40-L43) - If `fragmentCount` is smaller than `0`, it should default to `0`, not to `1`

The default scan time in the game is `1`. Making it shorter could cause problems.  
We could use a `Mathf.Max` instead for clarity.
>     [Handlers/CustomFishHandler.cs#L26](../blob/dev/3.0/QModManager/API/SMLHelper/Handlers/CustomFishHandler.cs#L26) - Does this need to be public?

This looks like it should be `internal`.
>     * [Handlers/CraftDataHandler.cs#L21-L43](../blob/dev/3.0/QModManager/API/SMLHelper/Handlers/CraftDataHandler.cs#L21-L43) - Duplicate `SetTechData` method. Class `TechData` inherits from `ITechData`

It may have been done this way for a backwards compatibility.  
It may have also been because we didn't always use the `ITechData` interface there, since this `TechData` class is from SMLHelper but the `ITechData` interface is from the base game.
