### ISSUE TITLE
Newest Version Causing Subnautica Launch Issues

### ISSUE THREAD

**Issue by mangafanatic** [QModManager/QModManager#111]
Not sure entirely what is going on, but at least with Vers. 2.1 it seems to be having some conflict with the newest Subnautica update: Big Little Update.  When installed, before adding any mods, it causes the game to not launch at all.  When the file integrity is validated, Steam states that two files were corrupted and needed to be re-downloaded.

Note: There were messages of a similar tone on Nexus, but I saw that as far as I could see, there were no messages here on GitHub. If you have gotten messages, my apologies for the duplicate error reports.

**Comment by AlexejheroYTB** [comment]
It actually woked fine with the Big Little update, but another update just dropped today that broke QModManager. We're aware of it, and we're working to fix it.

**Comment by ttr** [comment]
@AlexejheroYTB I've posted this on nexus forum - change log suggest that they update Mono to newest unstable (bleeding edge) ->  https://steamdb.info/patchnotes/4481813/

Would this mean that we're in longer wait ?

**Comment by PrimeSonic** [comment]
We are aware of the issue and are already working on an update.
We will make sure get it out as soon as possible.  
There is no need to continue adding to this thread.

**Comment by AlexejheroYTB** [comment]
The mono update should not be a problem.
We already have a half-working version of QModManager for the latest update.
> We will make sure get it out as soon as possible

**Comment by mangafanatic** [comment]
Thank you for your hard work.
