### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by legojoshua12** [QModManager/QModManager#18]
So my issue is that I am trying to get QMods working on mac, and I saw there were mac instructions.  Upon reading, I followed them step by step until I ran the command "mono QMods.exe" in my terminal.  It printed the error:
`Cannot open assembly 'QMods.exe': File does not contain a valid CIL image.`
I then decided to google an answer and found to do "mcs QMods.exe".  This created the error:
`error CS2015: Source file `QMods.exe' is a binary file and not a text file`
Does anyone have any info on what I am doing wrong or should try doing?  I would like this to work for mac, but I know you have stated in the past that a mac version was not on the horizon.  Any advice on what to do is greatly appreciated.

**Comment by AlexejheroYTB** [comment]
@Zebralear

**Comment by Zebralear** [comment]
Okay, @legojoshua12, Can I get a screenshot of your command input? That way I can see if you did anything wrong.

**Comment by legojoshua12** [comment]
Sure thing:
<img width="566" alt="screen shot 2018-08-11 at 1 01 08 pm" src="https://user-images.githubusercontent.com/11251167/43995650-b4c92974-9d66-11e8-9044-652350688a72.png">

**Comment by Qwiso** [comment]
From https://superuser.com/questions/489328/file-does-not-contain-a-valid-cil-image

> The mono command is used to run compiled C# programs. You need to compile hello.cs first with:
> 
> mcs hello.cs
> Then you can execute it with:
> 
> mono hello.exe
> For more information on writing C# programs with Mono see: http://www.codeproject.com/Articles/9407/Introduction-to-Mono-Your-first-Mono-app

**Comment by Qwiso** [comment]
Oh, look you need to compile the `.cs` not the `.exe`

**Comment by legojoshua12** [comment]
When I type mcs QMods.cs it says it can't find it, will the file be the original name of the downloaded one from nexus?

**Comment by Zebralear** [comment]
Okay, @legojoshua12 I’m working to get you the slightly edited files you need.

**Comment by Zebralear** [comment]
@qwiso, he doesn’t need to, the file isn’t the one that I had used. “Mono” was the correct command.

**Comment by legojoshua12** [comment]
Hey, so it has been a week and I was just wondering if I could have a bit of an idea of I should be waiting a long time for this or if it is something around the corner, no rush or anything.  I am just curious as to what is happening.

**Comment by legojoshua12** [comment]
@Zebralear if you can't get the installer working, I am ok with manually inserting the files into the place they need to go, if you could tell me where the source files have to go to override Subnautica code

**Comment by Zebralear** [comment]
Sorry, life’s been keeping me busy recently so I haven’t really had time. I’ll get you the file sometime tomorrow... @legojoshua12

**Comment by legojoshua12** [comment]
Yes, I was already on the modding discord and will send you a ping in a bit

**Comment by haaakon** [comment]
How did you guys fix this? I get the same problem with mono on mac

**Comment by legojoshua12** [comment]
https://drive.google.com/file/d/1XlVrPvRiXbjQEe_s1ZxXPLxiXGHW4IZb/view?usp=sharing
Download that and I wrote some instructions to go with it. None of that is mine, it came from Zebralear and his amazing magic.

**Comment by haaakon** [comment]
I'm getting an issue with versioning it seems. 

```
mono QModManager.exe
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319
Can't find custom attr constructor image: /Users/bogen/Library/Application Support/Steam/steamapps/common/Subnautica/Subnautica.app/Contents/Resources/Data/Managed/QModManager.exe mtoken: 0x0a00000c due to: Could not load file or assembly 'PresentationFramework, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies.
File name: 'Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'
  at QModInstaller.QModInjector.IsPatcherInjected () [0x00001] in <384cbfe373b34d2cbb99c78da3d73104>:0
  at QModManager.Program.Main (System.String[] args) [0x00113] in <ae3cc6de296d43d28baf96c6c3ce51ce>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies.
File name: 'Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'
  at QModInstaller.QModInjector.IsPatcherInjected () [0x00001] in <384cbfe373b34d2cbb99c78da3d73104>:0
  at QModManager.Program.Main (System.String[] args) [0x00113] in <ae3cc6de296d43d28baf96c6c3ce51ce>:
```

Maybe if the files are recompiled with never version of Mono it might work?

**Comment by legojoshua12** [comment]
No, that error has nothing to do with mono version actually.  What its saying is
`File name: 'Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'`
All you need is to remove your subnautica_data folder. Simply right click your subnautica.app and remove it. I recommend storing it on your desktop in case if you ever choose to uninstall qmods, then you can re-add it and play the vanilla game again.

**Comment by haaakon** [comment]
I could not find a folder named subnautica_data, thats the one that should be generated from the program running? Since it does not run, it might not be created?

**Comment by haaakon** [comment]
I've also tried uninstalling and reinstalling Subnautica from Steam, but does not seem to do any difference. Just to be clear, the subnautica_data folder should be in the containing folder of Subnautica.app ?

**Comment by AlexejheroYTB** [comment]
Reopened since it has gotten a lot of activity recently

**Comment by legojoshua12** [comment]
Oops, I gave you the wrong path. So sorry, the Subnautica_Data folder should be in the subnautica directory itself, right next to Subnautica.app.  That folder is the one you want to remove.  Your ultimate ending should look something like this.
<img width="589" alt="screen shot 2019-01-08 at 5 08 08 pm" src="https://user-images.githubusercontent.com/11251167/50869235-ff761a00-1367-11e9-8aa2-331deb4630f4.png">

**Comment by Testfliege** [comment]
<img width="983" alt="bildschirmfoto 2019-01-10 um 18 54 09" src="https://user-images.githubusercontent.com/15032607/50987322-a7771900-1509-11e9-9b12-dfbce165d0c3.png">

I'm getting a similar error, been following @Zebralear 's instructions by the book.

Any ideas?

**Comment by legojoshua12** [comment]
Those instructions given with the download are not fully complete and were neither written by Zebralear. I just wrote down what he had told me for help. Try the comment above and remove the Subnautica_Data folder from your subnautica directory and then do the install

**Comment by Testfliege** [comment]
I did, but it did not change the error that I got. I guess it's no mods for Mac then :/
<img width="674" alt="bildschirmfoto 2019-01-11 um 18 17 36" src="https://user-images.githubusercontent.com/15032607/51049027-f76ae400-15cc-11e9-8c4b-b199ae571958.png">

**Comment by Testfliege** [comment]
Ok, I did a clean install of Subnautica too, this is the file structure I get. 
<img width="673" alt="bildschirmfoto 2019-01-11 um 21 32 56" src="https://user-images.githubusercontent.com/15032607/51058257-7a4d6800-15e8-11e9-89ae-a1edbe1854fe.png">
There is no Subnautica_Data folder, not in the Steam/Subnautica directory or anywhere else on the drive. This is on a MacBook Pro running macOS 10.14.2. I installed Mono 5.18.0 (Stable channel) from https://www.mono-project.com/download/stable/. I uninstalled it and reinstalled Mono 5.16.0 (Visual Studio channel), getting the same results. Any ideas?

**Comment by acda3** [comment]
I had no Subnautica_Data folder, so I poked more and got it to work:  it requires Mono.Cecil dlls from version 0.9.6.0 in the current directory (which is not the latest), or installed generally.

Quick and dirty method:

nuget install Mono.Cecil -version 0.9.6.0
cp Mono.Cecil.0.9.6.0/lib/net40/* .
(optional:  "rm -rf Mono.Cecil.0.9.6.0" if you want to clean up your app folder)
```
[bite:Resources/Data/Managed] acd% mono QModManager.exe 
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319
Can't find custom attr constructor image: /Users/acd/Library/Application Support/Steam/steamapps/common/Subnautica/Subnautica.app/Contents/Resources/Data/Managed/QModManager.exe mtoken: 0x0a00000c due to: Could not load file or assembly 'PresentationFramework, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
No patch detected, type 'yes' to install: 
yes
QMods was installed!
Press any key to exit ...
```

However, I have no changes to the Subnautica install directory:
```
[bite:steamapps/common/Subnautica] acd% ls -l
total 16
drwxr-xr-x   5 acd  staff   160 Jan 11 12:57 AssetBundles
drwxr-xr-x  59 acd  staff  1888 Jan 11 12:57 OST
drwxr-xr-x  25 acd  staff   800 Jan 11 12:57 SNUnmanagedData
drwxr-xr-x   3 acd  staff    96 Jan 11 12:57 Subnautica.app
-rwxr-xr-x   1 acd  staff     5 Jan 11 12:57 __buildnumber.txt
-rwxr-xr-x   1 acd  staff    22 Jan 11 12:51 __buildtime.txt
[bite:steamapps/common/Subnautica] acd% find . -name QMods
[bite:steamapps/common/Subnautica] acd% 
```

**Comment by legojoshua12** [comment]
Right click on the Subnautica.app and see package contents. Maybe something is in there that’s causing the issue? This is starting to be outside my field of understanding

**Comment by acda3** [comment]
> Right click on the Subnautica.app and see package contents. Maybe something is in there that’s causing the issue? This is starting to be outside my field of understanding

See my previous post.  Is it possible that's it's trying to install to the wrong place?  Like a Windows path?  Or running it from the Data/Managed directory isn't the right place?  Or did it work, and I just need to manually create the QMods directory?

Is there a debug flag for the exe?  Maybe trace what it's actually doing since it doesn't seem to have installed anything.  I'm happy to do more troubleshooting, I'm just not sure where to go.

**Comment by acda3** [comment]
Seems to think it's done:
```
[bite:Resources/Data/Managed] acd% mono QModManager.exe 
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319
Can't find custom attr constructor image: /Users/acd/Library/Application Support/Steam/steamapps/common/Subnautica/Subnautica.app/Contents/Resources/Data/Managed/QModManager.exe mtoken: 0x0a00000c due to: Could not load file or assembly 'PresentationFramework, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
Patch already installed! Type 'yes' to remove: 
no
Press any key to exit ...
```

I manually created a QMods directory and dumped a bunch of mods in there (actually, I copied the directory from the Windows install), but nothing there in-game.  So something is clearly missing here.

**Comment by Testfliege** [comment]
OK, getting there
<img width="389" alt="bildschirmfoto 2019-01-11 um 23 33 25" src="https://user-images.githubusercontent.com/15032607/51062968-3020b280-15f9-11e9-91be-ade14cce2a16.png">
I moved the net40 files into Managed.
<img width="1074" alt="bildschirmfoto 2019-01-11 um 23 34 23" src="https://user-images.githubusercontent.com/15032607/51062994-4cbcea80-15f9-11e9-8f5d-287a83ecf5b3.png">

I added 3 mods (Mac version) to the QMods folder (Which I had to create), but nothing is changed in-game.

<img width="673" alt="bildschirmfoto 2019-01-11 um 23 43 11" src="https://user-images.githubusercontent.com/15032607/51063265-7fb3ae00-15fa-11e9-9983-157c3547ae4c.png">

**Comment by acda3** [comment]
Yep @Testfliege you're where I'm at now.

**Comment by legojoshua12** [comment]
Test the custom load screen mod, it will save you a whole lot of time and is really easy to notice, since you can quit right after to click load and see if it works or not

**Comment by Thomazella** [comment]
what I did:
`brew cask install mono-mdk` to get mono on mac
then I tried `mono __.exe` on the nexus file, it didn't work
then I got the file from the repo `Installer/QModManager/QModManager.exe`
Hit the `runtime version supported by this application is unavailable`
poked around, exe seems to want mono 2.0
downloaded mono 2.0 .dmg mac installer here: `https://download.mono-project.com/archive/2.0/download/`
ran `/Library/Frameworks/Mono.framework/Versions/2.0/bin/mono QModManager.exe`
got Assembly-CSharp.dll not found
tried with files from google drive posted here
got `Mono.Cecil not found error`
got file from repo `Installer/QModManager/Mono.Cecil.dll`
stuck at new got Assembly-CSharp.dll not found error lol

**Comment by Thomazella** [comment]
Let's get this to work gents, we're really close!

**Comment by legojoshua12** [comment]
Ok, after a full investigation, I was able to reproduce the error.  I have now solved it, and give me an hour to get the new code and instructions out, so everyone can use QMods on Mac. Its a little bit more involved.

**Comment by acda3** [comment]
Doing a fresh re-install just for good measure.  That will be about 15 more minutes, then I'll give this a try and update.  Thanks for your hard work on this!  It's much appreciated!

**Comment by AlexejheroYTB** [comment]
@legojoshua12 You can PR the updated mac installation instructions into the master branch when you are done.

**Comment by Testfliege** [comment]
<img width="1680" alt="bildschirmfoto 2019-01-13 um 20 57 32" src="https://user-images.githubusercontent.com/15032607/51089982-992d3500-1775-11e9-8a29-9c03ad385d72.png">

Did a clean install and followed through the instructions. Install went fine as previously, but still no QMods folder was created. I placed it manually and dropped the CLS-Mod, it doesn't show up in-game however. If I start a new game I get an error at the loading-screen and it will never move forward from there, necessitating a force-quit.

**Comment by legojoshua12** [comment]
Well, it looks like good things are happening to some degree because something happened. Let me try to replicate this.

**Comment by Testfliege** [comment]
Launching the game once however does now create a QMods folder if there wasn't one before. After placing the CLS-mod into it it will actually show up in-game, so this is good news indeed. Still getting the error message. 
<img width="1680" alt="bildschirmfoto 2019-01-13 um 21 11 21" src="https://user-images.githubusercontent.com/15032607/51090135-a1866f80-1777-11e9-9fe7-720417ca9965.png">

**Comment by legojoshua12** [comment]
Ok, so I am seeing if its simply an invalid reference to the folder location? I am not going to just send the world file over because thats 7 gb and no one wants to download that much, purely for testing.

**Comment by acda3** [comment]
Got it working.  Replacing the entire managed folder is too broad of a brush.  :)  You need the Assembly*.dll files, 0Harmony.dll and the Mono.Cecil.dll.  (The other mono files maybe, I'm not sure if they are part of the Subnautica distro or they were added, I'd already mucked with the folder by the time I was looking at it.)

For others testing it:  Try taking a clean install, following @legojoshua12's instructions EXCEPT don't remove/move the Managed directory entirely as stated, instead just copy all the files I mentioned above into it, plus the QMod* files from the zip file also, and the Mono folder from the zip into the directory one higher (Data/) (as stated in the instructions, no change here).  Now run the patch.

**Comment by legojoshua12** [comment]
Yep, that seems to be it. I just found the error and am working on replacing it. For now, that works well, and I will have the final version available here in a bit. I then will test it with a clean install so anyone can pick it up and do it without reading this long thread, and send it to the master branch.

**Comment by acda3** [comment]
```
Install Subnautica.
Download above file, and unzip in the Downloads folder.
Open Terminal
cd ~/Library/Application\ Support/Steam/steamapps/common/Subnautica/Subnautica.app/Contents/Resources/Data/Managed
mv ~/Downloads/QModManager\(Mac\)/Mono ../
mv ~/Downloads/QModManager\(Mac\)/Managed/Assembly-CSharp* .
mv ~/Downloads/QModManager\(Mac\)/Managed/0Harmony.dll .
mv ~/Downloads/QModManager\(Mac\)/Managed/Mono.Cecil.dll .
mv ~/Downloads/QModManager\(Mac\)/QMod* .
mono QModManager.exe
(type yes)
cd ../../../../..   (aka ~/Library/Application\ Support/Steam/steamapps/common/Subnautica/)
mkdir QMods
Put mods into QMods directory
Run Subnautica from Steam
```
Works, but with no sound.  Solution (I'm quite sure there's a better way):
```
cd - (back to Managed/ directory)
mono QModManager.exe
(type yes to uninstall the patch)
Use Steam's "Verify integrity of Local Files" function
mono QModManager.exe
(type yes to install the patch)
Run Subnautica from Steam
```
And now QMods works AND I have sound!  Yay!

**Comment by legojoshua12** [comment]
I opened #34 to add the documentation for mac users.

**Comment by Thomazella** [comment]
#34 worked perfectly here. While it's not merged and adding some clarifications:
- get QModManagerMac from [here](https://github.com/legojoshua12/QModManager/tree/master/QModManagerMac)
- click green button to download repo as zip (or `git clone`)
- follow instructions in #34

**Comment by acda3** [comment]
It is certainly possible that my sound issues have something to do with having "other than official" hardware.  So it might be worth noting for others that have a similar setup.

**Comment by legojoshua12** [comment]
I haven’t been able to replicate the sound issue so I can’t help much there.

**Comment by acda3** [comment]
> I haven’t been able to replicate the sound issue so I can’t help much there.

Eh, there's a workaround so I'm ok with it.  I'd suggest putting a note into the HowTo saying "if you have no sound after following these instructions, try this".

**Comment by Thomazella** [comment]
@acda3 you mean you have a hackintosh? I do and my sound is fine

**Comment by acda3** [comment]
> @acda3 you mean you have a hackintosh? I do and my sound is fine. If it's really an issue we'll get reports about it from more ppl IMO

Yes.  Weird.  Oh well.  I got it working in the end, so no worries.

**Comment by legojoshua12** [comment]
Mac Installation now has been merged with the master. Have fun using mods fellow mac users!

**Comment by jccmarkes** [comment]
How can i install mods in subnautica!? Tried the method with the Terminal, but my game doesn't open. It keep Crashing down and ask if i want to relauch, and then the same happens.... I have a Macbook Pro... Any ideias!? And most of the links here posted are broken, it gives the error 404 Page not found...

**Comment by djshire** [comment]
Just downloaded the pkg installer, and that worked.

However, the game will now just crash, not even load. Is the latest build available for download not compatible with the latest update?

**Comment by ZloyCotya** [comment]
I cannot register the command "mono QModManager"
<img width="578" alt="Снимок экрана 2021-02-04 в 9 13 26" src="https://user-images.githubusercontent.com/76115892/106839913-4b235b00-66c9-11eb-9c16-3016f59eaf94.png">

**Comment by Aus1273** [comment]
> Mac Installation now has been merged with the master. Have fun using mods fellow mac users!

@legojoshua12 I know you have probably moved on from the mac QMod years ago, but I will just post this. The mac Package installer works but subnautica doesnt anymore and just crashes as soon as you open it, am I doing a step wrong or the installer just out dated now?

**Comment by legojoshua12** [comment]
I have not touched much of any of this in a very long time.  Someone asked for help a few months ago and according to them it seemed to work fine with the package build over on my fork? It is a pretty old build of Qmods and I am unsure how many mods would even work with it if you decide to go down that route. The other option is to look into trying to do a manual install of the latest build and then making a fork in yourself if you decide to share the working instructions.  You are welcome to message me on discord and I can get around to helping out, maybe getting a newer version put out for the public but I am pretty unfamiliar with the code base.

**Comment by Aus1273** [comment]
Sorry to bother you again, the issue is that subnautica just crashes after starting, the actual package installer works fine

-Aus

**Comment by Aus1273** [comment]
> Sorry to bother you again, the issue is that subnautica just crashes after starting, the actual package installer works fine
> […](#)
> -Aus
Adding a Image
<img width="1440" alt="Screen Shot 2021-09-14 at 9 00 29 pm" src="https://user-images.githubusercontent.com/72693725/133262624-071695f1-b938-4b54-8eb8-ee251367cb43.png">
@legojoshua12, this is the error it gives me.
