### ISSUE TITLE
.NET Framework 3.5 missing

### ISSUE THREAD

**Issue by stimtheone** [QModManager/QModManager#49]
After installing QMods I do not notice the creation of the QMods folder. After creating it manually and introducing the folders for each mod in it there seems to be no gameplay impact, the map is not shown, no new crafting options appear, it seems the mod is nonfunctional. 

![qmods folder](https://user-images.githubusercontent.com/47397328/52364960-02d7f080-2a4f-11e9-8622-0bb2b343fddd.png)
![instal folder](https://user-images.githubusercontent.com/47397328/52364961-02d7f080-2a4f-11e9-823b-88ac4a83d0a9.png)

I'm running Windows 10 Pro, Regional settings are to English and UK. Game is Steam version.
After the installation of QMods I am prompted to install net framework 3.5, but windows 10 comes with a superior version of it and cannot downgrade

**Comment by AlexejheroYTB** [comment]
Please send a screenshot of the `Subnautica_Data/Managed` folder

**Comment by stimtheone** [comment]
![managed folder](https://user-images.githubusercontent.com/47397328/52365879-1edc9180-2a51-11e9-9eb1-0a418aac7b80.png)

**Comment by AlexejheroYTB** [comment]
Run `QModManager.exe` and type `yes`

**Comment by stimtheone** [comment]
I cannot. As sooon as I start it up a command prompt appears briefly before this taking its place
![prompt](https://user-images.githubusercontent.com/47397328/52366089-91e60800-2a51-11e9-97de-5514970fc8ce.png)

**Comment by AlexejheroYTB** [comment]
Oh, you don't have .NET 3.5
Click on Download and install this feature

**Comment by stimtheone** [comment]
![final result](https://user-images.githubusercontent.com/47397328/52366737-243adb80-2a53-11e9-9b4f-f2364fedc563.png)
In the attempt to install it either through that prompt, the manual package or by activating the feature in control panel, it cannot be done. But it seems a missing net framework 3.5 can cause it to not work and windows 10 has this problem where it is next to impossible to activate it

But it seems to be a windows problem, then. Time for a downgrade.

**Comment by PrimeSonic** [comment]
`How to Install the .NET Framework 3.5 on Windows 10, Windows 8.1, and Windows 8`
https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10
