### ISSUE TITLE
Runtime Error (at 55:357)

### ISSUE THREAD

**Issue by DilectableBananaButterfly** [QModManager/QModManager#52]
**Describe the problem**
Executing the installer results in a popup with the following error:
Runtime Error (at 55:357):
SWbemLocator: Server execution failed

All processes close after popup is dismissed.

**Additional info**
Windows 7, 64bit

**Comment by AlexejheroYTB** [comment]
I've never encountered this myself, can you please verify game contents then try again?

**Comment by DilectableBananaButterfly** [comment]
I've verified the files recently but did so again and ran the installer. Same error.

**Comment by DilectableBananaButterfly** [comment]
Anything else I should try? Any diagnostics I can do?

**Comment by AlexejheroYTB** [comment]
I've never seen an error like this before. Could you please send a screenshot of the popup and the installer?

**Comment by DilectableBananaButterfly** [comment]
Non Admin: 
- [Error](https://i.imgur.com/AvzYI7O.png)
- [Task List](https://i.imgur.com/wbviKHQ.png)

Admin: 
- [Error](https://i.imgur.com/sWVR6k5.png)
- [Task List](https://i.imgur.com/Z8KlCCu.png)

The QModManager-201-2-0-1550084275 installer doesn't seem to do make any alterations before faltering (Subnautica recognizes mods from the deprecated QMM) but if run as admin, Subnautica does not recognize that any mods are installed and the QModsSetup-16-1-2-1 installer has to be run (non-admin) to restore Subnautica's loading of mods.

**Comment by AlexejheroYTB** [comment]
A few things I should note:
 - You should **NEVER** downgrade to older versions of QModManager, because it might cause issues
 - The installer always needs to be run as administrator just in case Subnautica is installed in program files. I don't understand how you managed to not run it as non-admin, if you don't right click and run as admin, the program prompts admin access.

I don't know what might be causing this. This might be a windows issue.
 - What windows version do you have? (Right click computer, click properties, the version number should be somewhere on the page and it should have four digits)
 - What platform are you on? Steam/Epic/Discord
 - Are you trying to install it in the same drive as the Windows install drive? (Normally it's C:)
 - HDD OR SSD?

Some of this information might not be required, but until I can diagnose the issue, it is better to have as much information as possible.

**Comment by DilectableBananaButterfly** [comment]
>     * You should **NEVER** downgrade to older versions of QModManager, because it might cause issues

Well, it's reinstall the older version or I can't use mods in Subnautica

>     * The installer always needs to be run as administrator just in case Subnautica is installed in program files. I don't understand how you managed to not run it as non-admin, if you don't right click and run as admin, the program prompts admin access.

Because I made sure not to install the Epic Games app or Subnautica on the OS drive (*shiver*) (not that the Epic launcher doesn't put savegames out there ffs)

- Win7, as I stated before
- Epic
- Not sure how to answer that. The QMM 2.0 installer dies before it asks anything and the Epic Games launcher and subnautica are **not** installed on the OS drive (C:)
- HDD

**Comment by PrimeSonic** [comment]
https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/file-already-open-error-55
A quick search appears to indicate that this error in indicating that an already open file is attempting to be read by something else.  
@AlexejheroYTB Does this info help with diagnosing the issue?

Could the game be actively running?  
Is there some anti-virus or other program that is holding a lock on these files?

**Comment by AlexejheroYTB** [comment]
I'm not sure, I was looking [here](https://docs.microsoft.com/en-us/windows/desktop/WmiSdk/swbemlocator), but I couldn't find any useful information. I think the number `55` means the line number (probably something internal)

The game cannot be running, the installer would not start if that were the case.

About the antivirus, I have no idea.   
@DilectableBananaButterfly will need to answer that.

**Comment by DilectableBananaButterfly** [comment]
I initially thought it might be something that was still running/locked so I killed every process I thought I could get away with (obviously not firewall/av) and got the same error. I thought it might be something that it expects to be running and isn't but I  couldn't determine what that might be. I can't imagine what file could possibly be open.

"at 55:357" sounds more the location rather than the error itself (since it has text to give the error), otherwise I'd expect "55 at 357" or something.

The file winds up with a we-don't-have-many-people-running-this-program-so-you-might-not-want-to flag but I instruct it to run anyway (since it's already cleared the AV scan) and it doesn't give any other responses.

Is there a runtime package for VB that I might need? (grasping at straws)

Is this trying to make a connection over the network?

**Comment by AlexejheroYTB** [comment]
> "at 55:357" sounds more the location rather than the error itself (since it has text to give the error), otherwise I'd expect "55 at 357" or something.

Yea, it sounds like a location. Maybe in the internal build script or something...

> Is there a runtime package for VB that I might need? (grasping at straws)

Do you have .NET Framework 3.5?

> Is this trying to make a connection over the network?

Nope


I'm stumped. I don't know what could be causing this. I will reply to this issue if I have more information.

**Comment by DilectableBananaButterfly** [comment]
Windows Features shows 3.5.1 (w/ comm options disabled), and Microsoft.NET folder shows 3.5 (and a few others)

**Comment by AlexejheroYTB** [comment]
Yea, I have no clue. Have you managed to get it to work?

**Comment by DilectableBananaButterfly** [comment]
Yes...
...but not by the method I'd prefer: new computer w/ win10. Network port irreplaceably failed, and with new mb/cpu comes new OS; I can't consider it 'solved' but rather 'obviated', so if no one else has reported the error, you might as well close issue.

**Comment by AlexejheroYTB** [comment]
I'll keep this issue in mind if I ever see something similar. Thanks for reporting

**Comment by AlexejheroYTB** [comment]
@DilectableBananaButterfly Are you still having this issue?
