### ISSUE TITLE
Mouse stuck in center of screen / loss of cursor

### ISSUE THREAD

**Issue by Pompsama** [QModManager/QModManager#59]
**Describe the problem**
After installation, launching the game locks the mouse in the middle of the screen, along with the cursor no longer being visible. Uninstalling through the .dat or QModManager restores vanilla game functionality.

**Additional info**
The background of the titlescreen also gets distorted with QMod active, it just becomes a flat, matte blue color.

**Comment by AlexejheroYTB** [comment]
Known issue. Will be fixed in the next update

**Comment by AlexejheroYTB** [comment]
Unfortunately there are currently no workarounds available

**Comment by AlexejheroYTB** [comment]
Unless... are you on Steam, Epic, or Discord?
