### ISSUE TITLE
Entirely Broke My Entire Game 

### ISSUE THREAD

**Issue by Lethalityh** [QModManager/QModManager#61]
Okay what the actual heck. I downloaded this to be able to use a mod in Subnautica but little did I know this was some Malware (not really but close enough) stuff. It bugged my entire game and rid all progress I've made. What game? The game I can't even load at the moment because I am 'luckily' stuck at the loading... page for literally all of eternity. Fix your mod or don't publish it, very upset with how this turned out. Do not download this unless you'd like to lose literally everything; like I did. I downloaded this, and I can't even delete the file. No matter what I do it comes back and ensures that my previous saves and fun times spent building and playing in this game were entirely eradicated. What the actual heck man. Can someone tell me how to fix this? I'd like to actually be able to play the darn game
**Screenshots**
![image](https://user-images.githubusercontent.com/47937039/53296193-4d3fc800-37d8-11e9-8e6a-5ee3b1a89050.png)
^ stupid loading screen that lasts three thousand decades

**Comment by kylinator25** [comment]
Do you have nitrox installed?

**Comment by Lethalityh** [comment]
Yea, I do

**Comment by kylinator25** [comment]
Nitrox and QMods dont work together

**Comment by Lethalityh** [comment]
Okay but like what do I do

**Comment by kylinator25** [comment]
To fix this, simply verify your game files. Your saves will not be affected

**Comment by Lethalityh** [comment]
Thanks but how, I have no idea what I'm doing

**Comment by kylinator25** [comment]
Are you on steam or epic?

**Comment by Lethalityh** [comment]
Steam

**Comment by kylinator25** [comment]
Well, simply right click the game in your library, select Properties > Local Files > Verify Integrity of Game Files.

In the future, I suggest doing some research before submitting a random outburst at someone else

**Comment by Lethalityh** [comment]
f okay thanks my dude lol, life saver

**Comment by Lethalityh** [comment]
I would've done research but I have no idea what even happened, thanks again though
