### ISSUE TITLE
Issue installing QModManager

### ISSUE THREAD

**Issue by Razaelvae** [QModManager/QModManager#65]
Running the QModManager instillation application doesn't load all the files into the Subnautica, I am running windows 10, have disabled all protections and running the file as an Administrator. The folder is in the standard steam directory and I am not receiving any error messages related to this, please advise.

**Comment by kylinator25** [comment]
QModManager puts files into the Subnautica_Data/Managed folder, you're saying there arent any there?

**Comment by legojoshua12** [comment]
What do you mean by:

> doesn't load all the files into the Subnautica

what files are being loaded if any? Have you tried a manual installation as well or are you using Nitrox? Nitrox does not work with qmods if so and you must uninstall nitrox first

**Comment by Razaelvae** [comment]
The files themselves weren't appearing or loading, I uninstalled Subnautica and reinstalled and everything works now, thank you.

**Comment by Razaelvae** [comment]
Thank you for your time.
