### ISSUE TITLE
Installer cannot import InstallerExtensions.dll

### ISSUE THREAD

**Issue by prestonpeterson** [QModManager/QModManager#68]
This is the first thing that happens when I try to run the v2.0.1 installer on Windows 10.

Full error:
```
Runtime error (at -1:0):

Cannot import dll:<utf8>C:\Users\Preston\AppData\Local\Temp\is-CQFN9.tmp\InstallerExtensions.dll.
```
Each time I run it, it has a different name for the "is-\*\*\*\*\*.tmp" folder in the above path. It is always "is-" followed by a 5 character sequence of random upper case letters and numbers. Some kind of hash maybe? Not sure if that's relevant, just something I noticed.
In any case, neither this dll nor this "is-*****.tmp" folder exists in my AppData/Local/Temp directory.

Also tried running the installer as admin but same error occurs.

**Comment by devinmartin** [comment]
I had the same issue. I looked through the code and noticed that everything is targeting .net 3.5. Once I installed the older .net 3.5 framework everything worked properly.

https://www.microsoft.com/en-us/download/details.aspx?id=21

**Comment by AlexejheroYTB** [comment]
Fixed in the next update
