### ISSUE TITLE
Add dependency on .net 3.5 in the install shield script

### ISSUE THREAD

**Issue by devinmartin** [QModManager/QModManager#69]
**Describe the issue**
If the machine has a 4.x version of the .net framework but not 3.5 the installer wont work. It will fail with an unhelpful message (see #68).

Since Subnautica seems to include some sort of prepackaged mono run-time it isn't installed as part of the game even though 3.5 is the required version for the game.

This is a very detectable scenario. I propose adding a dependency on .net 3.5 in the .iss file in the installer

**Comment by AlexejheroYTB** [comment]
Thanks for letting us know what the cause of the issue was. We don't necessarily need to add a .net 3.5 dependency to the installer, we could just update the installer to use .net 4.x. The mod manager itself cannot be updated though, as Subnautica uses .net 3.5.

**Comment by AlexejheroYTB** [comment]
I'll see what I can do

**Comment by devinmartin** [comment]
I'm not entirely convinced that you don't need to install 3.5. You are correct, you could update the installerextensions.dll to be 4.x, but the overall executable still needs to be 3.5 because like you say, the subnautica game is 3.5. Since you run the modloader exe INSTEAD of the game and use it to bootstrap the game but with patching, I still think you'll need 3.5.

**Comment by AlexejheroYTB** [comment]
The executable itself can, in fact, target net 4.x. The executable just handles injecting/uninjecting, and it does that using Mono, so there wouldn't be any reason for it to not work in 4.x. The dll file, on the other hand, needs to be 3.5.

**Comment by AlexejheroYTB** [comment]
Will be a thing in the next update
