### ISSUE TITLE
Trouble building QModManager_Setup.exe

### ISSUE THREAD

**Issue by jonatanYanovsky** [QModManager/QModManager#70]
I opened the project within Visual Studio, Build > Build Solution, but QModManager_Setup.exe does not get built. 

Instead, only the following files get built (into the Build folder, checked by Date Modified, setup.exe was never modified):
InstallerExtensions.dll
QModInstaller.dll
QModInstaller.pdb
QModManager.exe
QModManager.pdb

I'm wondering what steps I'm missing to build the final version of the setup executable?

**Comment by AlexejheroYTB** [comment]
Open the `Installer/QModsInstallerScript.iss` in Inno Setup and click Compile (or F9) to build the .exe

**Comment by jonatanYanovsky** [comment]
> Open the `Installer/QModsInstallerScript.iss` in Inno Setup and click Compile (or F9) to build the .exe

Thanks @AlexejheroYTB

**Comment by AlexejheroYTB** [comment]
If your question has been answered, you should close the issue
