### ISSUE TITLE
Missing assembly reference when trying to build project

### ISSUE THREAD

**Issue by crazyTauron** [QModManager/QModManager#71]
Hi, I haven't used VS for many years and I need some clarification. I clone the project from github, I open it with Visual Studio and I didn't change anything but if i try to build the entire project(or single part except InstallerExtensions) it didn't compile and give me some error like FMODUnity not found(i googled FMODUnity but what i found not work) or RuntimeManager/UWE/DevConsole not exist. 
Where am I doing wrong?

Thanks

**Comment by AlexejheroYTB** [comment]
QModManager references "Assembly-CSharp.dll" and "Assembly-CSharp-firstpass.dll".
Go into "Subnautica_Data/Managed", copy these two files, and paste them into the "Dependencies" folder in the cloned project, then restart vs

**Comment by crazyTauron** [comment]
You are awsome! Thank you
