### ISSUE TITLE
No such file directory issue

### ISSUE THREAD

**Issue by KhajiitGotYourBack** [QModManager/QModManager#80]
Problem
When trying to Install this on mac i get the following issue in terminal
cp: QmodManagerMac/*: No such file or directory
**Screenshots**
![Issue qmod](https://user-images.githubusercontent.com/50278700/57185965-56cb6780-6ece-11e9-87ea-a3ce40166474.png)

contact me on discord https://discord.gg/a9s49jm i wont be on from 11am to 12pm central europen time

**Comment by KhajiitGotYourBack** [comment]
if you comment i will be asleep so i wont reply

**Comment by AlexejheroYTB** [comment]
The instructions on the GitHub page are outdated. You can't copy the contents of the QModManagerMac directory _because there is no QModManagerMac directory_. You will need to manually download some files.

@legojoshua12 will be able to tell you which files are required for a manual mac installation

**Comment by KhajiitGotYourBack** [comment]
ok

**Comment by legojoshua12** [comment]
Before I go into how to install manually, you can use the installer found [here](https://github.com/QModManager/QModManager/tree/mac-installer/Mac%20Installation) for an easier route.

For manual installation, the instructions have fallen out of use. Some rough instructions are as follows:
1. Download the latest stable build of QModManager off of the master branch
2. Copy the four files in the folder "build" to 

> ~/Library/Application\ Support/Steam/SteamApps/common/Subnautica/Subnautica.app/Contents/Resources/Data/Managed/
3. Now open up terminal and navigate to that directory above
4. Type Mono QModManager.exe
5. Allow for QMods to install, then close the terminal
6. You should have a new folder called QMods created in the Subnautica Directory, this is where you can put mods

If you have any more questions, please feel free to ask me on discord in the modding tab, just mention me so I see it

**Comment by quin-q** [comment]
@legojoshua12 do you happen to know how this works these days? the installer link is a 404 now, and i can't work out what i need to download
