### ISSUE TITLE
QModManager does not recognize .NET 3.5

### ISSUE THREAD

**Issue by CoreTheCoder** [QModManager/QModManager#96]
**Describe the problem**
I have .NET 3.5.1 installed. Running Windows 7.

**Screenshots**
![image](https://user-images.githubusercontent.com/51146991/58528838-527d2c00-81a6-11e9-8c45-b8bb9644f1fd.png)

**Additional info**
Checked everything. I'm a .NET developer.

**Comment by AlexejheroYTB** [comment]
Yes, we did not account for this.

**Comment by CoreTheCoder** [comment]
Thanks for the response. I'll keep an eye out for an updated installer.

**Comment by AlexejheroYTB** [comment]
Could you please show me a screenshot of your `v3.5` registry folder?

**Comment by CoreTheCoder** [comment]
That's what's attached in my original message.

**Comment by AlexejheroYTB** [comment]
I meant the base `v3.5` folder, not the `1033` folder

**Comment by CoreTheCoder** [comment]
Oh, lol. It's late. Gottcha.

![image](https://user-images.githubusercontent.com/51146991/58529779-37acb680-81aa-11e9-8ff6-15001823c927.png)

**Comment by CoreTheCoder** [comment]
I gotta hit the sack. I'll check back in the AM. Best of luck and thanks for looking into this!

**Comment by AlexejheroYTB** [comment]
Okay, this is actually weird. From what I can tell, it should be detected correctly.

**Comment by AlexejheroYTB** [comment]
Okay so, news - after inspecting the script I could not find anything that could lead to this error. I have checked my registry and confirmed that it works as it should. Please show me a screenshot of the error that you receive.

**Comment by CoreTheCoder** [comment]
You got it. Here is everything:

![image](https://user-images.githubusercontent.com/51146991/58565461-c6e2ba00-81fc-11e9-9272-6942f7486e29.png)

![image](https://user-images.githubusercontent.com/51146991/58565475-d19d4f00-81fc-11e9-978f-a052fd035d3d.png)

Once UAC is accepted. This box pops up almost instantly.

![image](https://user-images.githubusercontent.com/51146991/58565418-ab77af00-81fc-11e9-89af-2e29754adc45.png)

**Comment by CoreTheCoder** [comment]
Interesting, even VS is throwing this:

![image](https://user-images.githubusercontent.com/51146991/58565750-46708900-81fd-11e9-8d34-97d4eba40634.png)

**Comment by CoreTheCoder** [comment]
I'm now shifting into tracking down WHY it would say i have it, but can't use it in VS.

**Comment by AlexejheroYTB** [comment]
[This](https://github.com/QModManager/QModManager/blob/master/Installer/QModsInstallerScript.iss#L464-L539) is the function that checks for the .NET version.

If VS says that it's missing, it probably is. Check to see if it is enabled from the `Turn Windows features on or off` menu.

![image](https://user-images.githubusercontent.com/32238504/58566251-eb5c8780-8238-11e9-9495-f3c9084ded8c.png)
![image](https://user-images.githubusercontent.com/32238504/58566299-0cbd7380-8239-11e9-8d42-a4b480250336.png)

**Comment by CoreTheCoder** [comment]
That was the first thing i did. It looks a little different on win 7 but it WAS there. I just removed it in an attempt to reinstall that exact feature.

**Comment by CoreTheCoder** [comment]
This is AFTER uninstalling it. (it was properly checked before) Here is the uninstalled cap of the reg post uninstall:

![image](https://user-images.githubusercontent.com/51146991/58566516-cba86d80-81fe-11e9-814e-1c676553fe55.png)

It's not listed in NDP any more. Gone.. as it should be. 

Will now attempt to reinstall 3.5.

**Comment by AlexejheroYTB** [comment]
From the registry, the installer only checks if the `Install` key is `1`.

![image](https://user-images.githubusercontent.com/32238504/58566601-9bca8b80-8239-11e9-9106-cf90a2fa295e.png)

The only other explanation is that the registry could not be queried for the key.

**Comment by CoreTheCoder** [comment]
And here it is again after reinstall of the feature:

![image](https://user-images.githubusercontent.com/51146991/58567074-b08a2d80-81ff-11e9-8f65-e1c728f407f8.png)

I'd imagine if there was something wrong with the reg as global as "unable to read" it would impact.. tons of stuff. I program in .NET mostly without issues. I do exclusively work in .NET 4.0 and above though. 

I install .. loads of stuff. Steam library has over 2000 games? I have a few hundred installed right now. Never had a reg related issue of that nature so i'm more inclined to believe it's something else. I'm continuing to work on it. Seeing if i can can get source to load and eventually compile.

**Comment by AlexejheroYTB** [comment]
Did you reboot your computer after installing?

**Comment by AlexejheroYTB** [comment]
The only thing I can find on the internet related to this issue is [this](https://superuser.com/questions/106647/net-framework-3-5-sp1-on-windows-7-not-recognized-by-installers), but from what I understand you've already tried it.

**Comment by CoreTheCoder** [comment]
It worked!

Took a few to reboot. 

Uninstall and reinstall of 3.5 via windows features was what did it. No idea WHY seeing as how the reg seems fine before the uninstall reinstall.

**Comment by CoreTheCoder** [comment]
I can also target frame works older than .NET 4.0 in VS2017 now. 

Thanks for your help Alex. Keep up the great work!
